name=W25N_Flash_library
version=0.1.0
author=Mark Stanley
maintainer=Community https://github.com/Nullkraft/W25N_Flash_library
sentence=W25N01GV 3V 1G-BIT SERIAL SLC NAND FLASH MEMORY driver library
paragraph=Read and write functions are provided at the highest level. You can select the address and read and write your data
category=DataStorage
url=https://github.com/Nullkraft/W25N_Flash_library
architectures=*
